### ISSUE TITLE
Improve progress event computation

### ISSUE THREAD

**Issue by xavierfoucrier** [andreupifarre/preload#2]
The **progression value should be computed based on the total file sizes** instead of the fetch array length.

Currently, if you got 5 items in the fetch array with 4 of 1Kb and 1 of 10Mb, the preload will compute a progression value of 80% when reaching the fifth element... that is, for certain use cases, not really the expected result.

May be a custom property like `computation: 'length' | 'filesize'` should be added to allow the user to choose between the different computation methods.

**Comment by andreupifarre** [comment]
Thanks for the suggestion it makes a lot of sense to provide with the ablility to choose any of both computational methods

**Comment by andreupifarre** [comment]
I have added an option `stepped` which is `true` by default, that computes the files like individual steps, `false` will move the progress in a linear way, considering the total amount of bytes to fetch for all files

**Comment by xavierfoucrier** [comment]
Hi @andreupifarre,

Not really sure the wording you choose will talk to every developer.
Anyway, thanks for the fix :wink:
