### ISSUE TITLE
Cancel method and event

### ISSUE THREAD

**Issue by xavierfoucrier** [andreupifarre/preload#4]
Allow the user to properly cancel the preload at any time by calling `preload.cancel()`, aborting the `XMLHttpRequest`. Add support for a cancel event too, like `preload.canceled = () => { ... }`.

**Comment by andreupifarre** [comment]
This has been added already on `1.4.0`, `preload.cancel()` method and `preload.oncancel = items => {}` event.

**Comment by xavierfoucrier** [comment]
Thanks @andreupifarre!
> that wasn't specified in the doc on january
