### ISSUE TITLE
How to preload assets from relative path?

### ISSUE THREAD

**Issue by FateRiddle** [andreupifarre/preload#5]
```js
import Preload from 'preload-it';
const preload = Preload();
preload
  .fetch([
    'https://xxx/TB1GYDruxnaK1RjSZFtXXbC2VXa-750-640.png',
    '../../mods/image/male-sprites.png',
  ])
  .then((items) => {
    console.log(items);
  });
``` 
So it can load the first image, but fail to find the second one. The error is either:
1. preload-it.js?f99a:25 Uncaught TypeError: Cannot set property 'blobUrl' of undefined, or
2. 404 not found.

**Comment by FateRiddle** [comment]
Also am I able to name the images in fetch? You see we may have some random generated name for the assets as show in my code, but I really want to name it, and pick it up in my oncomplete, I do think it is a helpful feature in general.

**Comment by andreupifarre** [comment]
preload-it uses `XMLHttpRequest` to retrieve data from a URL, this can be relative or absolute, they both are allowed.
