### ISSUE TITLE
There is no failed event.

### ISSUE THREAD

**Issue by al03** [andreupifarre/preload#6]
What if the network or url of download file is not correct, the download can't competed all download.

**Comment by andreupifarre** [comment]
If a file request receives an error like a 404 for example, it will throw the corresponding error on the browser console, but the file will be bypassed and ignored for computation purposes, so other files can continue loading.
If the file is blocked by CORS policy, it will get stuck, I may try to find a solution for that at some point, feel free to contribute if you have a nice fix for it.

**Comment by andreupifarre** [comment]
I have added an event `onerror` that will trigger if a request returns 404, more states can be added, but for now it will do the trick
